### ISSUE TITLE
BE crashes when game ends

### ISSUE THREAD

**Issue by santiagotena** [Poonehmgh/ft_transcendence#94]
<img width="868" alt="image" src="https://github.com/Poonehmgh/ft_transcendence/assets/10122847/79b2b4a1-5099-42e7-babb-4f3390e56757">

**Comment by statvej** [comment]
The game crushes because not the refference, but the socket itself is stored in the game object which is getting deleted after game ends
Solution:
put the list of the users with their sockets outside of the game

**Comment by statvej** [comment]
the issue turns out to be on frontend side and all backend changes are irrelevant
